set -g default-terminal "screen-256color"

unbind C-b
set -g prefix ` 
bind-key ` send-prefix

set -g mouse on

unbind %
bind '\' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

unbind r 
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# move pane (swap)
# bind -r H swap-pane -L     # move pane to the left
# bind -r L swap-pane -R     # move pane to the right
# bind -r J swap-pane -D     # move pane down
# bind -r K swap-pane -U     # move pane up

# Copy vim movements
# set-window-option -g mode-keys vi

#bind-key -T copy-mode-vi 'v' send -X begin-selection
#bind-key -T copy-mode-vi 'y' send -X copy-selection

# unbind -T copy-mode-vi MouseDragEnd1Pane

# new window
bind c new-window -c '#{pane_current_path}'

# start from 1, not 0
set-option -g base-index 1
# re-number when closing windows
set-option -g renumber-windows on

# open a note for billion $ idea
# bind -r e split-window -h "nvim ~/Documents/git/scratch/notes_$(date +'%Y%m%d%H').md"
# bind -r v split-window -h -c "#{pane_current_path}" "zsh -c 'nvim; exec zsh'"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# save tmux session even tmux-server is killed
# leader + ctrl + s for saving
# leader + ctrl + r for reload
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'catppuccin/tmux#v2.1.2'
# set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'xamut/tmux-weather'

# Options to make tmux more pleasant
# set -g mouse on
# set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "basic"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`

set -g window-status-separator ""  # Removes the space between windows
set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text "#[bg=#{@thm_mantle}] #{b:pane_current_path}"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text "#W" # show path for active panes, fallback to app name
set -g @catppuccin_window_number_color "#{@thm_lavender}"

set -g status-left "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]#S "
set -g status-style fg=default,bg=default
set -g status-interval 60
set -g status-right-length 80 #character length

set -ag status-right "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application} #[fg=#{@thm_fg},bg=#{@thm_mantle}] quoc.ta ☆*: .｡. o(≧▽≦)o .｡.:*☆ "
set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] %y/%m/%d:%H "
set -agF status-right "#[fg=#{@thm_green}]"
